version: '3'

services:
  agendaDB:
    image: postgres:15.3
    container_name: agenda-medica-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agenda-medica
    volumes:
      - ./postgres:/var/lib/postgresql/data

